/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "tertiary": "#c5e7ff",
        "inverse-primary": "#6f5d00",
        "surface-dim": "#18160d",
        "on-surface-variant": "#cfc6ac",
        "inverse-on-surface": "#343025",
        "inverse-surface": "#e9e2d1",
        "on-tertiary": "#00344b",
        "on-primary-container": "#ffe163",
        "on-primary-fixed-variant": "#544600",
        "secondary": "#d9c680",
        "error-container": "#93000a",
        "on-tertiary-fixed": "#001e2d",
        "surface-container": "#2a2718",
        "on-tertiary-container": "#c6e7ff",
        "on-error": "#690005",
        "surface-variant": "#4c4733",
        "primary-container": "#544600",
        "on-error-container": "#ffdad6",
        "primary": "#e6c419",
        "on-secondary": "#3a3000",
        "outline": "#989079",
        "background": "#211e11",
        "surface-container-highest": "#413c29",
        "on-secondary-fixed": "#221b00",
        "surface-container-high": "#353120",
        "on-primary-fixed": "#221b00",
        "on-secondary-container": "#cab873",
        "surface-bright": "#3d392d",
        "surface-container-lowest": "#110e05",
        "tertiary-container": "#004c6b",
        "on-tertiary-fixed-variant": "#004c6b",
        "tertiary-fixed-dim": "#81cfff",
        "on-primary": "#211e11",
        "secondary-fixed": "#f6e299",
        "on-background": "#e9e2d1",
        "secondary-container": "#55480e",
        "outline-variant": "#4c4733",
        "primary-fixed": "#ffe167",
        "on-surface": "#e9e2d1",
        "secondary-fixed-dim": "#d9c680",
        "surface-container-low": "#211e11",
        "tertiary-fixed": "#c6e7ff",
        "error": "#ffb4ab",
        "on-secondary-fixed-variant": "#53460c",
        "surface-tint": "#e6c419",
        "surface": "#211e11",
        "primary-fixed-dim": "#e7c41a"
      },
      fontFamily: {
        "headline": ["Manrope", "sans-serif"],
        "body": ["Manrope", "sans-serif"],
        "label": ["Manrope", "sans-serif"],
        "manrope": ["Manrope", "sans-serif"]
      },
      borderRadius: {"DEFAULT": "0.25rem", "lg": "0.5rem", "xl": "0.75rem", "full": "9999px"},
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/container-queries')
  ],
}
